=== ARERA-it/vettoriamento_gas/FlussoFattureGas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

<!-- INIZIO TIPI SEMPLICI -->
<!-- testata flusso -->
<xs:simpleType name="FlussoType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="V"/>
    <xs:enumeration value="R"/>
  </xs:restriction>
</xs:simpleType>

<!-- data e ora -->
<xs:simpleType name="DataOraType">
  <xs:restriction base="xs:string">
    <xs:length value="19"/>
    <xs:pattern value="\d{4}[-]\d{2}[-]\d{2}[T]\d{2}:\d{2}:\d{2}"/>
  </xs:restriction>
</xs:simpleType>

<!-- data -->
<xs:simpleType name="DataType">
  <xs:restriction base="xs:string">
    <xs:length value="10"/>
    <xs:pattern value="\d{4}[-]\d{2}[-]\d{2}"/>
  </xs:restriction>
</xs:simpleType>

<!-- versione -->
<xs:simpleType name="VersioneType">
  <xs:restriction base="xs:string">
    <xs:pattern value="\d{1,3}[.]\d{1,3}"/>
  </xs:restriction>
</xs:simpleType>

<!-- numero sequenza -->
<xs:simpleType name="NumeroSequenzaType">
  <xs:restriction base="xs:string">
    <xs:minLength value="1"/>
    <xs:pattern value="\d{1,6}"/>
  </xs:restriction>
</xs:simpleType>

<!-- booleano -->
<xs:simpleType name="BooleanoType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="SI"/>
    <xs:enumeration value="NO"/>
  </xs:restriction>
</xs:simpleType>

<!-- partita iva -->
<xs:simpleType name="PIVAType">
  <xs:restriction base="xs:string">
    <xs:pattern value="\w"/><!-- [A-Z]{2}?\d{11} -->
  </xs:restriction>
</xs:simpleType>

<!-- codice fiscale -->
<xs:simpleType name="CodiceFiscaleType">
  <xs:restriction base="xs:string">
    <xs:minLength value="1"/>
    <xs:maxLength value="16"/>

    <!-- <xs:pattern value="\w{16}"/> tutte cifre? -->
  </xs:restriction>
</xs:simpleType>

<!-- testo fino a 128 caratteri -->
<xs:simpleType name="Testo128Type">
  <xs:restriction base="xs:string">
    <xs:minLength value="1"/>
    <xs:maxLength value="128"/>
  </xs:restriction>
</xs:simpleType>

<!-- CAP -->
<xs:simpleType name="CAPType">
  <xs:restriction base="xs:string">
    <xs:pattern value="\d{5}"/>
  </xs:restriction>
</xs:simpleType>

<!-- localita -->
<xs:simpleType name="LocalitaType"><!-- converto in 64? -->
  <xs:restriction base="xs:string">
    <xs:minLength value="1"/>
    <xs:maxLength value="60"/>
  </xs:restriction>
</xs:simpleType>

<!-- provincia -->
<xs:simpleType name="ProvinciaType">
  <xs:restriction base="xs:string">
    <xs:pattern value="[A-Z]{2}"/>
  </xs:restriction>
</xs:simpleType>

<!-- nazione -->
<xs:simpleType name="NazioneType">
  <xs:restriction base="xs:string">
    <xs:pattern value="[A-Z]{3}"/>
  </xs:restriction>
</xs:simpleType>

<!-- email -->
<xs:simpleType name="EmailType">
  <xs:restriction base="xs:string">
    <xs:pattern value="[^@]+@[^@]+\.[^@]+"/>
  </xs:restriction>
</xs:simpleType>

<!-- telefono -->
<xs:simpleType name="TelefonoType">
  <xs:restriction base="xs:string">
    <xs:pattern value="\d{1,32}"/>
  </xs:restriction>
</xs:simpleType>

<!-- testo fino a 256 caratteri -->
<xs:simpleType name="Testo256Type">
  <xs:restriction base="xs:string">
    <xs:minLength value="1"/>
    <xs:maxLength value="256"/>
  </xs:restriction>
</xs:simpleType>

<!-- IBAN -->
<xs:simpleType name="IBANType">
  <xs:restriction base="xs:string">
    <xs:minLength value="15"/>
    <xs:maxLength value="34"/>
  </xs:restriction>
</xs:simpleType>

<!-- importo -->
<xs:simpleType name="ImportoType">
  <xs:restriction base="xs:string">
    <xs:pattern value="[+-]?[0-9]{1,9},[0-9]{2}"/>
  </xs:restriction>
</xs:simpleType>

<!-- importo -->
<xs:simpleType name="NoteFatturaType">
  <xs:restriction base="xs:string">
    <xs:minLength value="0"/>
    <xs:maxLength value="10000"/>
  </xs:restriction>
</xs:simpleType>

<!-- categoria voce fattura -->
<xs:simpleType name="CategoriaVoceFatturaType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="xxx"/><!-- TODO: completa la lista -->
  </xs:restriction>
</xs:simpleType>

<!-- riferimento IVA fattura -->
<xs:simpleType name="RiferimentoIVAType">
  <xs:restriction base="xs:string">
    <xs:minLength value="1"/>
    <xs:maxLength value="16"/>
  </xs:restriction>
</xs:simpleType>

<!-- codice PDR -->
<xs:simpleType name="CodicePDRType">
  <xs:restriction base="xs:string">
    <xs:minLength value="1"/>
    <xs:maxLength value="14"/>
  </xs:restriction>

<!-- codice REMI Pool -->
<xs:simpleType name="REMIPoolType">
  <xs:restriction base="xs:string">
    <xs:minLength value="1"/>
    <xs:maxLength value="32"/>
  </xs:restriction>

<!-- codice ISTAT -->
<xs:simpleType name="CodiceISTATType">
  <xs:restriction base="xs:string">
    <xs:pattern value="\d{6}"/>
  </xs:restriction>
</xs:simpleType>

<!-- coefficiente correttivo -->
<xs:simpleType name="CoefficienteCType">
  <xs:restriction base="xs:string">
    <xs:pattern value="\d{1}[,]\d{1,6}"/>
  </xs:restriction>
</xs:simpleType>

<!-- progressivo anno solare -->
<xs:simpleType name="ProgrAnnoSolareType">
  <xs:restriction base="xs:string">
    <xs:pattern value="\d{1,6}[,]\d{1,3}"/>
  </xs:restriction>
</xs:simpleType>

<!-- classe del misuratore -->
<xs:simpleType name="ClasseMisuratoreType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="G4"/>
    <xs:enumeration value="G6"/>
    <xs:enumeration value="G10"/>
    <xs:enumeration value="G16"/>
    <xs:enumeration value="G25"/>
    <xs:enumeration value="G40"/>
    <xs:enumeration value="G65"/>
    <xs:enumeration value="G100"/>
    <xs:enumeration value="G160"/>
    <xs:enumeration value="G250"/>
    <xs:enumeration value="G400"/>
    <xs:enumeration value="G650"/>
    <xs:enumeration value="G1000"/>
    <xs:enumeration value="G1600"/>
    <xs:enumeration value="G2500"/>
    <xs:enumeration value="G4000"/>
    <xs:enumeration value="AO_GT_G40"/>
    <xs:enumeration value="AO_LOE_G40"/>
  </xs:restriction>
</xs:simpleType>

<!-- tipo PDR -->
<xs:simpleType name="PDRType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="CLI-DOM"/>
    <xs:enumeration value="CON-DOM"/>
    <xs:enumeration value="SERV-PUB"/>
    <xs:enumeration value="USI-DIV"/>
  </xs:restriction>
</xs:simpleType>

<!-- ambito tariffario -->
<xs:simpleType name="AmbitoTariffarioType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="TUTTI"/>
    <xs:enumeration value="N-OCC"/>
    <xs:enumeration value="N-ORI"/>
    <xs:enumeration value="CENTR"/>
    <xs:enumeration value="S-ORI"/>
    <xs:enumeration value="S-OCC"/>
    <xs:enumeration value="MERID"/>
    <xs:enumeration value="SARD"/>
  </xs:restriction>
</xs:simpleType>

<!-- importo PDR, tipo movimento -->
<xs:simpleType name="TipoMovimentoType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="F"/>
    <xs:enumeration value="S"/>
  </xs:restriction>
</xs:simpleType>

<!-- importo PDR, componente tariffaria -->
<xs:simpleType name="ComponenteTariffariaType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="F"/>
    <xs:enumeration value="S"/>
  </xs:restriction>
</xs:simpleType>

<!-- importo PDR, regime compensazione bonus -->
<xs:simpleType name="RegimeCompensazioenBonusType">
  <xs:restriction base="xs:string">
    <xs:pattern value="[A-Z]{7}"/><!-- TODO: verifica come Ã¨ effettivamente -->
  </xs:restriction>
</xs:simpleType>

<!-- codice Bonus SII -->
<xs:simpleType name="CodiceBonusType">
  <xs:restriction base="xs:string">
    <xs:minLength value="1"/>
    <xs:maxLength value="15"/>
  </xs:restriction>

<!-- Valore numerico, fino a 6 cifre nella parte intera e fino a 6 cifre nella parte decimale -->
<xs:simpleType name="SeiVSeiType">
  <xs:restriction base="xs:string">
    <xs:pattern value="\d{1,6}[,]\d{1,6}"/>
  </xs:restriction>
</xs:simpleType>

<!-- Valore numerico, fino a 9 cifre nella parte intera e fino a 6 cifre nella parte decimale -->
<xs:simpleType name="NoveVSeiType">
  <xs:restriction base="xs:string">
    <xs:pattern value="\d{1,9}[,]\d{1,6}"/>
  </xs:restriction>
</xs:simpleType>

<!-- Scaglione -->
<xs:simpleType name="ScaglioneType">
  <xs:restriction base="xs:string">
    <xs:pattern value="[1-9]"/>
  </xs:restriction>
</xs:simpleType>


<xs:simpleType name="CategoriaVoceFatturataType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="tau1_dis"/>
    <xs:enumeration value="tau1_mis"/>
    <xs:enumeration value="tau1_cot"/>
    <xs:enumeration value="tau3_dis"/>
    <xs:enumeration value="gs"/>
    <xs:enumeration value="comp_tar_re"/>
    <xs:enumeration value="rs"/>
    <xs:enumeration value="ug1"/>
    <xs:enumeration value="ug2c_f"/>
    <xs:enumeration value="ug2c_v"/>
    <xs:enumeration value="ug2k_f"/>
    <xs:enumeration value="ug2k_v"/>
    <xs:enumeration value="ug3int"/>
    <xs:enumeration value="ug3ft"/>
    <xs:enumeration value="ug3ui"/>
    <xs:enumeration value="st"/>
    <xs:enumeration value="vr"/>
    <xs:enumeration value="ce"/>
    <xs:enumeration value="can_com"/>
    <xs:enumeration value="bonus_soc"/>
    <xs:enumeration value="ex_cci"/>
    <xs:enumeration value="deltat1cot"/>
    <xs:enumeration value="comp_alpha"/>
    <xs:enumeration value="comp_beta"/>
    <xs:enumeration value="contri_fini_fisc"/>
    <xs:enumeration value="qf_ante_2009"/>
    <xs:enumeration value="qv_ante_2009"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="ModalitaPagamentoType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="MP01"/>
    <xs:enumeration value="MP02"/>
    <xs:enumeration value="MP03"/>
    <xs:enumeration value="MP04"/>
    <xs:enumeration value="MP05"/>
    <xs:enumeration value="MP06"/>
    <xs:enumeration value="MP07"/>
    <xs:enumeration value="MP08"/>
    <xs:enumeration value="MP09"/>
    <xs:enumeration value="MP10"/>
    <xs:enumeration value="MP11"/>
    <xs:enumeration value="MP12"/>
    <xs:enumeration value="MP13"/>
    <xs:enumeration value="MP14"/>
    <xs:enumeration value="MP15"/>
    <xs:enumeration value="MP16"/>
    <xs:enumeration value="MP17"/>
    <xs:enumeration value="MP18"/>
    <xs:enumeration value="MP19"/>
    <xs:enumeration value="MP20"/>
    <xs:enumeration value="MP21"/>
    <xs:enumeration value="MP22"/>
    <xs:enumeration value="MP23"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="CondizioniPagamentoType"><!-- TODO: questo non Ã¨ un tipo complesso! -->
  <xs:restriction base="xs:string">
    <xs:enumeration value="TP01"/>
    <xs:enumeration value="TP02"/>
    <xs:enumeration value="TP03"/>
  </xs:restriction>
</xs:simpleType>

<!-- FINE TIPI SEMPLICI -->


<!-- INIZIO TIPI COMPLESSI -->
<xs:complexType name="TestataFlussoType">
  <xs:sequence>
    <xs:element name="TipoFlusso" type="FlussoType"/>
    <xs:element name="DataCreazione" type="DataType"/>
    <xs:element name="Versione" type="VersioneType"/>
    <xs:element name="NumeroSequenza" type="NumeroSequenzaType"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="MittenteType">
  <xs:sequence>
    <xs:element name="RagioneSociale" type="Testo128Type"/>
    <xs:element name="PartitaIVA" type="PIVAType"/>
    <xs:element name="PartitaIVAGruppo" type="PIVAType" minOccurs="0"/>
    <xs:element name="CodiceFiscale" type="CodiceFiscaleType"/>
    <xs:element name="Indirizzo" type="IndirizzoType"/>
    <xs:element name="Email" type="EmailType" minOccurs="0"/>
    <xs:element name="Telefono" type="TelefonoType" minOccurs="0"/>
    <xs:element name="Pagamento" type="PagamentoType"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="IndirizzoType">
  <xs:sequence>
    <xs:element name="Intestazione" type="Testo128Type" minOccurs="0"/>
    <xs:element name="Indirizzo" type="Testo128Type"/>
    <xs:element name="CAP" type="CAPType"/>
    <xs:element name="Localita" type="LocalitaType"/>
    <xs:element name="Provincia" type="ProvinciaType"/>
    <xs:element name="Nazione" type="NazioneType"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="PagamentoType">
  <xs:sequence>
    <xs:element name="CondizioniPagamento" type="CondizioniPagamentoType" minOccurs="0"/>
    <xs:element name="ModalitaPagamento" type="ModalitaPagamentoType"/>
    <xs:element name="IBAN" type="IBANType"/>
  </xs:sequence>
</xs:complexType>


<xs:complexType name="DestinatarioType">
  <xs:sequence>
    <xs:element name="RagioneSociale" type="Testo128Type"/>
    <xs:element name="PartitaIVA" type="PIVAType"/>
    <xs:element name="PartitaIVAGruppo" type="PIVAType" minOccurs="0"/>
    <xs:element name="CodiceFiscale" type="CodiceFiscaleType"/>
    <xs:element name="IndirizzoFatturazione" type="IndirizzoType"/>
    <xs:element name="IndirizzoSpedizione" type="IndirizzoType" minOccurs="0"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="FatturaType">
  <xs:sequence>
    <xs:element name="DataEmissione" type="DataType"/>
    <xs:element name="DataScadenza" type="DataType"/>
    <xs:element name="TotaleImponibile" type="ImportoType"/>
    <xs:element name="TotaleIVA" type="ImportoType"/>
    <xs:element name="Totale" type="ImportoType"/>
    <xs:element name="ImportoBollo" type="ImportoType"/>
    <xs:element name="Note" type="NoteFatturaType" minOccurs="0"/>
    <xs:element name="VociFattura" type="VoceFatturaType" maxOccurs="unbounded"/>
    <xs:element name="RiferimentiIVA" type="RiferimentoIVAType" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>


<xs:complexType name="VoceFatturaType">
  <xs:sequence>
    <xs:element name="CategoriaVoceFatturata" type="CategoriaVoceFatturataType"/>
    <xs:element name="CodiceRiferimentoIVA" type="RiferimentoIVAType"/>
    <xs:element name="Imponibile" type="ImportoType"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="RiferimentoIVAType">
  <xs:sequence>
    <xs:element name="Codice" type="RiferimentoIVAType"/>
    <xs:element name="Descrizione" type="Testo128Type"/>
    <xs:element name="Aliquota" type="ImportoType"/>
  </xs:sequence>
</xs:complexType>


<xs:complexType name="CategoriaVoceFatturataType">
  <xs:sequence>
    <xs:element name="CategoriaVoceFatturata" type="CategoriaVoceFatturataType"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="DettagliPDRType">
  <xs:sequence>
    <xs:element name="DettaglioPDR" type="DettaglioPDRType" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="ImportiType">
  <xs:sequence>
    <xs:element name="Importo" type="ImportoType" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="ImportoType">
  <xs:sequence>
    <xs:element name="DataInizio" type="DataType"/>
    <xs:element name="DataFine" type="DataType"/>
    <xs:element name="TipoMovimento" type="TipoMovimentoType"/>
    <xs:element name="ComponenteTariffaria" type="DataType"/>
    <xs:element name="RegimeCompensazioneBonus" type="RegimeCompensazioenBonusType" minOccurs="0"/>
    <xs:element name="CodiceBonusSII" type="CodiceBonusType"/>
    <xs:element name="Quota" type="SeiVSeiType"/>
    <xs:element name="Scaglione" type="ScaglioneType" minOccurs="0"/>
    <xs:element name="Quantita" type="NoveVSeiType"/>
    <xs:element name="Imponibile" type="NoveVSeiType"/>
  </xs:sequence>
</xs:complexType>


<xs:complexType name="DettaglioPDRType">
  <xs:sequence>
    <xs:element name="CodicePDR" type="CodicePDRType"/>
    <xs:element name="RemiPool" type="REMIPoolType"/>
    <xs:element name="CodiceISTAT" type="CodiceISTATType"/>
    <xs:element name="Comune" type="LocalitaType" minOccurs="0"/>
    <xs:element name="CoefficienteC" type="CoefficienteCType" minOccurs="0"/>
    <xs:element name="Correttore" type="BooleanoType"/>
    <xs:element name="ProgrAnnoSolare" type="ProgrAnnoSolareType"/>
    <xs:element name="ClasseMisuratore" type="ClasseMisuratoreType"/>
    <xs:element name="TipoPDR" type="PDRType"/>
    <xs:element name="AmbitoTariffario" type="AmbitoTariffarioType"/>
    <xs:element name="Importi" type="ImportiType"/>
  </xs:sequence>
</xs:complexType>


<!--  -->
<xs:complexType name="ChiusuraFlussoType">
  <xs:sequence>
    <xs:element name="UltimoElementoSequenza" type="BooleanoType" default="NO"/>
  </xs:sequence>
</xs:complexType>

<!-- FINE TIPI COMPLESSI -->


<!-- INIZIO ELEMENTO PRINCIPALE -->
<xs:element name="FlussoFattureTrasportoGas">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="TestataFlusso" type="TestataFlussoType"/>
      <xs:element name="Mittente" type="MittenteType"/>
      <xs:element name="Destinatario" type="DestinatarioType"/>
      <xs:element name="Fattura" type="FatturaType"/>
      <xs:element name="DettagliPDR" type="DettagliPDRType"/>
      <xs:element name="ChiusuraFlusso" type="ChiusuraFlussoType"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<!-- FINE ELEMENTO PRINCIPALE -->

=== ARERA-it/vettoriamento_gas/empty_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<FlussoFattureTrasportoGas 
    xmlns:xsi="https://www.w3.org/2001/XMLSchema" 
    xsi:noNamespaceSchemaLocation="FlussoFattureGas.xsd">
    
  <TestataFlusso>
    <TipoFlusso></TipoFlusso>
    <DataCreazione></DataCreazione>
    <Versione></Versione>
    <NumeroSequenza></NumeroSequenza>
  </TestataFlusso>

  <Mittente>
    <RagioneSociale></RagioneSociale>
    <PartitaIVA></PartitaIVA>
    <PartitaIVAGruppo></PartitaIVAGruppo>
    <CodiceFiscale></CodiceFiscale>
    <Indirizzo>
      <Intestazione></Intestazione>
      <Indirizzo></Indirizzo>
      <CAP></CAP>
      <Localita></Localita>
      <Provincia></Provincia>
      <Nazione></Nazione>
    </Indirizzo>
    <Email></Email>
    <Telefono></Telefono>
    <Pagamento>
      <CondizioniPagamento></CondizioniPagamento>
      <ModalitaPagamento></ModalitaPagamento>
      <IBAN></IBAN>
    </Pagamento>
  </Mittente>

  <Destinatario>
    <RagioneSociale></RagioneSociale>
    <PartitaIVA></PartitaIVA>
    <PartitaIVAGruppo></PartitaIVAGruppo>
    <CodiceFiscale></CodiceFiscale>
    <IndirizzoFatturazione>
      <Intestazione></Intestazione>
      <Indirizzo></Indirizzo>
      <CAP></CAP>
      <Localita></Localita>
      <Provincia></Provincia>
      <Nazione></Nazione>
    </IndirizzoFatturazione>
    <IndirizzoSpedizione>
      <Intestazione></Intestazione>
      <Indirizzo></Indirizzo>
      <CAP></CAP>
      <Localita></Localita>
      <Provincia></Provincia>
      <Nazione></Nazione>
    </IndirizzoSpedizione>
  </Destinatario>

  <Fattura>
    <Numero></Numero>
    <DataEmissione></DataEmissione>
    <DataScadenza></DataScadenza>
    <TotaleImponibile></TotaleImponibile>
    <TotaleIVA></TotaleIVA>
    <Totale></Totale>
    <ImportoBollo></ImportoBollo>
    <Note></Note>

    <VociFattura>
      <VoceFattura>
        <CategoriaVoceFatturata></CategoriaVoceFatturata>
        <CodiceRiferimentoIVA></CodiceRiferimentoIVA>
        <Imponibile></Imponibile>
      </VoceFattura>
    </VociFattura>

    <RiferimentiIVA>
      <RiferimentoIVA>
        <Codice></Codice>
        <Descrizione></Descrizione>
        <Aliquota></Aliquota>
      </RiferimentoIVA>
      <RiferimentoIVA>
        <Codice></Codice>
        <Descrizione></Descrizione>
        <Aliquota></Aliquota>
      </RiferimentoIVA>
    </RiferimentiIVA>
  </Fattura>

  <DettagliPDR>
    <DettaglioPDR>
      <CodicePDR></CodicePDR>
      <REMIPool></REMIPool>
      <CodiceISTAT></CodiceISTAT>
      <Comune></Comune>
      <CoefficienteC></CoefficienteC>
      <Correttore></Correttore>
      <ProgrAnnoSolare></ProgrAnnoSolare>
      <ClasseMisuratore></ClasseMisuratore>
      <TipoPDR></TipoPDR>
      <AmbitoTariffario></AmbitoTariffario>
      <Importi>
        <Importo>
          <DataInizio></DataInizio>
          <DataFine></DataFine>
          <TipoMovimento></TipoMovimento>
          <ComponenteTariffaria></ComponenteTariffaria>
          <RegimeCompensazioneBonus></RegimeCompensazioneBonus>
          <CodiceBonusSII></CodiceBonusSII>
          <Quota></Quota>
          <Scaglione></Scaglione>
          <Quantita></Quantita>
          <Imponibile></Imponibile>
        </Importo>
    </DettaglioPDR>
  </DettagliPDR>

  <ChiusuraFlusso>
    <UltimoElementoSequenza></UltimoElementoSequenza>
  </ChiusuraFlusso>
</FlussoFattureTrasporto>

=== ARERA-it/vettoriamento_gas/full_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<FlussoFattureTrasportoGas 
    xmlns:xsi="https://www.w3.org/2001/XMLSchema" 
    xsi:noNamespaceSchemaLocation="FlussoFattureGas.xsd">
    
  <TestataFlusso>
    <TipoFlusso>V</TipoFlusso>
    <DataCreazione>2023-11-20T17:48:25</DataCreazione>
    <Versione>1.0</Versione>
    <NumeroSequenza>1</NumeroSequenza>
  </TestataFlusso>

  

  <Mittente>
    <RagioneSociale></RagioneSociale>
    <PartitaIVA></PartitaIVA>
    <PartitaIVAGruppo></PartitaIVAGruppo>
    <CodiceFiscale></CodiceFiscale>
    <Indirizzo>
      <Intestazione></Intestazione>
      <Indirizzo></Indirizzo>
      <CAP></CAP>
      <Localita></Localita>
      <Provincia></Provincia>
      <Nazione></Nazione>
    </Indirizzo>
    <Email></Email>
    <Telefono></Telefono>
    <Pagamento>
      <Condizioni></Condizioni>
      <Metodo></Metodo>
      <IBAN></IBAN>
    </Pagamento>
  </Mittente>

  <Destinatario>
    <RagioneSociale></RagioneSociale>
    <PartitaIVA></PartitaIVA>
    <PartitaIVAGruppo></PartitaIVAGruppo>
    <CodiceFiscale></CodiceFiscale>
    <IndirizzoFatturazione>
      <Intestazione></Intestazione>
      <Indirizzo></Indirizzo>
      <CAP></CAP>
      <Localita></Localita>
      <Provincia></Provincia>
      <Nazione></Nazione>
    </IndirizzoFatturazione>
    <IndirizzoSpedizione>
      <Intestazione></Intestazione>
      <Indirizzo></Indirizzo>
      <CAP></CAP>
      <Localita></Localita>
      <Provincia></Provincia>
      <Nazione></Nazione>
    </IndirizzoSpedizione>
  </Destinatario>

  <Fattura>
    <Numero></Numero>
    <DataEmissione></DataEmissione>
    <DataScadenza></DataScadenza>
    <TotaleImponibile></TotaleImponibile>
    <TotaleIVA></TotaleIVA>
    <Totale></Totale>
    <ImportoBollo></ImportoBollo>
    <Note></Note>

    <VociFattura>
      <VoceFattura>
        <Categoria></Categoria>
        <RiferimentoIVA></RiferimentoIVA>
        <Imponibile></Imponibile>
      </VoceFattura>
    </VociFattura>

    <RiferimentiIVA>
      <RiferimentoIVA>
        <Codice></Codice>
        <Descrizione></Descrizione>
        <Valore></Valore>
      </RiferimentoIVA>
      <RiferimentoIVA>
        <Codice></Codice>
        <Descrizione></Descrizione>
        <Valore></Valore>
      </RiferimentoIVA>
    </RiferimentiIVA>
  </Fattura>

  <DettagliPDR>
    <DettaglioPDR>
      <CodicePDR></CodicePDR>
      <REMIPool></REMIPool>
      <CodiceISTAT></CodiceISTAT>
      <Comune></Comune>
      <CoefficienteC></CoefficienteC>
      <Correttore></Correttore>
      <ProgAnnoSolare></ProgAnnoSolare>
      <ClasseMisuratore></ClasseMisuratore>
      <Tipo></Tipo>
      <AmbitoTariffario></AmbitoTariffario>
      <Importi>
        <Importo>
          <DataInizio></DataInizio>
          <DataFine></DataFine>
          <TipoMovimento></TipoMovimento>
          <ComponenteTariffaria></ComponenteTariffaria>
          <RegimeCompensazioneBonus></RegimeCompensazioneBonus>
          <CodiceBonusSII></CodiceBonusSII>
          <Quota></Quota>
          <Scaglione></Scaglione>
          <Quantita></Quantita>
          <Imponibile></Imponibile>
        </Importo>
    </DettaglioPDR>
  </DettagliPDR>

  <ChiusuraFlusso>
    <UltimoElementoSequenza>SI</UltimoElementoSequenza>
  </ChiusuraFlusso>
</FlussoFattureTrasporto>
